sudo: required
language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: '6b2762fa66757aecc2494fa7f20a6e6465134014dca2d02bef935f41af410907'
notifications:
  email: false
before_install:
  - sudo sysctl vm.max_map_count=262144
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.3/elasticsearch-2.4.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.3.deb && sudo service elasticsearch restart
before_script:
  - sleep 10
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
