dist: trusty
sudo: required
language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: 'f7898d1d1ca2b76715bc35cc3ba880b35e3fbdc07c3aeb27ca98eecb5e5c064d'
notifications:
  email: false
before_install:
  - sudo sysctl vm.max_map_count=262144
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.0.2.deb && sudo service elasticsearch restart
before_script:
  - sleep 10
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
